spring.application.name=Nexora-backend
spring.datasource.url=jdbc:postgresql://localhost:5431/nexora_db
spring.datasource.username=postgres
spring.datasource.password=nexora_dev

spring.jpa.hibernate.ddl-auto=validate

spring.jpa.open-in-view=false

spring.flyway.enabled=true